export const en = {
  GETTING_STARTED: 'Getting Started',
  GETTIN_STARTED_HELPER_TEXT: 'This guide provides examples showing how to add our components to your pages and helps you use these components correctly in your projects.',
  DRAWER_COMPONENT: 'Drawer Component',
  BUTTON_COMPONENT: 'Button Component',
  TEXT_COMPONENT: 'Text Component',
  CODEBLOCK_COMPONENT: 'CodeBlock Component',
  DRAWER_COMPONENT_INFO: 'The Drawer component opens a bottom drawer on the page, allowing you to render your components without leaving the active window.',
  HOW_TO_USE: 'How to Use?',
  DRAWER_TITLE: 'Drawer Title',
  DRAWER_SUBTITLE: 'Drawer Subtitle',
  CONTENT_VIEW_DESCRIPTION: 'Content Will Be Displayed Here',
  PROPERTIES: 'Properties',
  DRAWER_CODEBLOCK: 'navigation.navigate("BottomDrawerScreen", {\n  title: "Drawer Title",\n   subtitle: "Drawer Subtitle",\n  children: <Text>Content Will Be Displayed Here</Text>,\n  fixed: false,\n});',
  DRAWER_CODEBLOCK_BUTTON: '<BPButton title="Open Drawer" onPress={handleOpen} color="#238636" />',
  DRAWER_TITLE_DESCRIPTION: 'The drawer title is displayed in large text at the top.',
  DRAWER_SUBTITLE_DESCRIPTION: 'A description added under the title.',
  DRAWER_CHILDREN_DESCRIPTION: 'Content that is dynamically rendered inside the drawer.',
  DRAWER_FIXED_DESCRIPTION: 'If true, the drawer cannot be closed and remains fixed.',
};
