export const tr = {
  GETTING_STARTED: 'Başlarken',
  GETTIN_STARTED_HELPER_TEXT:'Bu kılavuz, bileşenlerimizi sayfalara nasıl ekleyebileceğinizi gösteren örnekler sunmaktadır ve projelerinizde bu bileşenleri doğru şekilde kullanmanıza yardımcı olacaktır.',
  DRAWER_COMPONENT: 'Drawer Bileşeni',
  BUTTON_COMPONENT: 'Button Bileşeni',
  TEXT_COMPONENT: 'Text Bileşeni',
  CODEBLOCK_COMPONENT: 'CodeBlock Bileşeni',
  DRAWER_COMPONENT_INFO:'Drawer bileşeni, sayfa içerisinde bir bottom drawer açarak aktif pencereden ayrılmadan bileşenlerinizi render etmenizi sağlar.',
  HOW_TO_USE: 'Nasıl Kullanılır?',
  DRAWER_TITLE: 'Drawer Başlığı',
  DRAWER_SUBTITLE: 'Drawer Açıklaması',
  CONTENT_VIEW_DESCRIPTION: 'İçerik Burada Gösterilecek',
  PROPERTIES: 'Özellikler',
  DRAWER_CODEBLOCK:'navigation.navigate("BottomDrawerScreen", {\n  title: "Drawer Başlığı",\n   subtitle: "Drawer Açıklaması",\n  children: <Text>İçerik Burada Gösterilecek</Text>,\n  fixed: false,\n});',
  DRAWER_CODEBLOCK_BUTTON:'<BPButton title="Drawer Aç" onPress={handleOpen} color="#238636" />',
  DRAWER_TITLE_DESCRIPTION: 'Drawer başlığı, üst kısımda büyük yazı ile gösterilir.',
  DRAWER_SUBTITLE_DESCRIPTION: 'Başlığın altına eklenen açıklama metni.',
  DRAWER_CHILDREN_DESCRIPTION: 'Drawer içerisinde yer alan, dinamik olarak render edilen içerik.',
  DRAWER_FIXED_DESCRIPTION: 'Eğer true ise, drawer kapatılamaz ve sabit kalır.',
};
